name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  DEV_AZURE_IMAGE_NAME: naseh-lawfirm
  DEV_AZURE_REGISTRY: nasehtestcontainerregistry.azurecr.io

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Login to Azure CLI
      - name: Login to Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
